"""
Pydantic models for LLM-generated Explanations.
"""
from pydantic import BaseModel, Field


class LLMExplanation(BaseModel):
    """Structured explanation generated by the LLM."""
    parent_message: str = Field(..., description="Clear, empathetic explanation for parents")
    suggested_next_step: str = Field(..., description="Actionable next step for the family")
    clinician_note: str = Field(..., description="Technical note summarizing risk factors for clinicians")
    
    model_config = {"from_attributes": True}
